export const images = {
  yourlogo: "/assets/verity.png",
  check: "/assets/check.svg",
  check2: "/assets/check-02.svg",
  loading1: "/assets/loading-01.svg",
  starForgeSymbol: "/assets/starforge-symbol.svg",
  starForgeWhiteSymbol: "/assets/starforge-symbol-white.svg",
  play: "/assets/play.svg",
  gradient: "/assets/gradient.png",
  smallSphere: "/assets/4-small.png",
  grid: "/assets/grid.png",
  homeSmile: "/assets/home-smile.svg",
  file02: "/assets/file-02.svg",
  searchMd: "/assets/search-md.svg",
  plusSquare: "/assets/plus-square.svg",
  recording03: "/assets/recording-03.svg",
  recording01: "/assets/recording-01.svg",
  disc02: "/assets/disc-02.svg",
  chromecast: "/assets/chrome-cast.svg",
  sliders04: "/assets/sliders-04.svg",
  loading: "/assets/verity.png",
  background: "/assets/background.jpg",
  curve: "/assets/hero/curve.png",
  robot: "/assets/hero/Gemini_Generated_Image_lcumtilcumtilcum.png",
  heroBackground: "/assets/hero/hero-background.jpg",
  curve1: "/assets/collaboration/curve-1.svg",
  curve2: "/assets/collaboration/curve-2.svg",
  discord: "/assets/collaboration/discord.png",
  figma: "/assets/collaboration/figma.png",
  collabFacebook: "/assets/collaboration/facebook.png",
  collabInstagram: "/assets/collaboration/instagram.png",
  photoshop: "/assets/collaboration/photoshop.png",
  twitch: "/assets/collaboration/twitch.png",
  whatsapp: "/assets/collaboration/whatsapp.png",
  youtube: "/assets/collaboration/YouTube.png",
  service1: "/assets/services/service-1.png",
  service2: "/assets/services/service-2.png",
  service3: "/assets/services/service-3.png",
  lines: "/assets/pricing/lines.svg",
  stars: "/assets/pricing/stars.svg",
  coins: "/assets/roadmap/coins.png",
  done: "/assets/roadmap/done.svg",
  hero: "/assets/roadmap/hero.png",
  roadmap1: "/assets/roadmap/detailed-fingerprint.png",
  roadmap2: "/assets/roadmap/image-2.png",
  roadmap3: "/assets/roadmap/image-3.png",
  roadmap4: "/assets/roadmap/flow.png",
  undone: "/assets/roadmap/undone.svg",
  notification1: "/assets/notification/image-1.png",
  notification2: "/assets/notification/image-2.png",
  notification3: "/assets/notification/image-3.png",
  notification4: "/assets/notification/image-4.png",
  benefitCard1: "/assets/benefits/card-1.svg",
  benefitCard2: "/assets/benefits/card-2.svg",
  benefitCard3: "/assets/benefits/card-3.svg",
  benefitCard4: "/assets/benefits/card-4.svg",
  benefitCard5: "/assets/benefits/card-5.svg",
  benefitCard6: "/assets/benefits/card-6.svg",
  benefitIcon1: "/assets/benefits/icon-1.svg",
  benefitIcon2: "/assets/benefits/icon-2.svg",
  benefitIcon3: "/assets/benefits/icon-3.svg",
  benefitIcon4: "/assets/benefits/icon-4.svg",
  benefitImage2: "/assets/benefits/image-2.png",
  discordBlack: "/assets/socials/discord.svg",
  facebook: "/assets/socials/facebook.svg",
  instagram: "/assets/socials/instagram.svg",
  telegram: "/assets/socials/telegram.svg",
  twitter: "/assets/socials/twitter.svg",
};

const {
  yourlogo,
  homeSmile,
  file02,
  searchMd,
  plusSquare,
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
  discord,
  figma,
  photoshop,
  twitch,
  whatsapp,
  youtube,
  collabFacebook,
  collabInstagram,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  notification2,
  notification3,
  notification4,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  discordBlack,
  facebook,
  instagram,
  telegram,
  twitter,
} = images;

export const navigation = [
  { id: "0", title: "Modules", url: "#features" },
  { id: "1", title: "Pricing", url: "#pricing" },
  { id: "2", title: "Workflow", url: "#how-to-use" },
  { id: "3", title: "Architecture", url: "#roadmap" },
  { id: "4", title: "Sign In", url: "#login", onlyMobile: true },
  { id: "5", title: "Dashboard", url: "#login", onlyMobile: true },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [
  { logo: yourlogo, name: "Verity", tagline: "Deepfake Forensics" },
  { logo: yourlogo, name: "Verity", tagline: "Asset Vault Security" },
  { logo: yourlogo, name: "Verity", tagline: "Perceptual Fingerprinting" },
  { logo: yourlogo, name: "Verity", tagline: "Vertex Match Engine" },
  { logo: yourlogo, name: "Verity", tagline: "AI Content Authenticity" },
];

export const starForgeServices = [
  "Vertex Similarity Match",
  "Anomaly Detection",
  "Automated DMCA Notices",
];

export const starForgeServicesIcons = [
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
];

export const roadmap = [
  {
    id: "0",
    title: "Layer 1: Vault Authentication",
    text: "Biometically secured asset storage. Generates persistent digital signatures (pHash, dHash) and grants encrypted access to verified owners.",
    date: "Deployed",
    status: "done",
    imageUrl: "/assets/roadmap/custom-vault.png",
    colorful: true,
  },
  {
    id: "1",
    title: "Layer 2: AI Embeddings",
    text: "Processes each asset using Vertex AI Vision to generate a 512-dimensional embedding vector, solving modifications and deepfakes.",
    date: "Deployed",
    status: "done",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Layer 3: DCT Watermarking",
    text: "Embeds an invisible watermark directly into the frequency domain surviving JPEG recompression, cropping, and reposting.",
    date: "Deployed",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Deepfake Detection Layer",
    text: "Advanced AI integration to identify face swapping, voice cloning, and GAN-generated textures in near real-time.",
    date: "Deployed",
    status: "done",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "With near real-time detection, Verity scales to monitor over 10 million assets across the entire web simultaneously.";

export const collabContent = [
  { id: "0", title: "Continuous Platform Monitoring", text: collabText },
  { id: "1", title: "Automated Takedown Notices" },
  { id: "2", title: "Immutable Asset Vault" },
];

export const collabApps = [
  { id: "0", title: "Figma",      icon: images.figma,           width: 36, height: 36 },
  { id: "1", title: "Discord",   icon: images.discord,         width: 36, height: 36 },
  { id: "2", title: "Photoshop", icon: images.photoshop,       width: 36, height: 36 },
  { id: "3", title: "YouTube",   icon: images.youtube,         width: 36, height: 36 },
  { id: "4", title: "Instagram", icon: images.collabInstagram, width: 36, height: 36 },
  { id: "5", title: "Facebook",  icon: images.collabFacebook,  width: 36, height: 36 },
  { id: "6", title: "Twitch",    icon: images.twitch,          width: 36, height: 36 },
  { id: "7", title: "WhatsApp",  icon: images.whatsapp,        width: 36, height: 36 },
];

export const pricing = [
  {
    id: "0",
    title: "Basic Vault",
    description: "Ideal for independent creators tracking portfolios",
    price: "0",
    features: [
      "Protect up to 1,000 digital assets",
      "Standard pHash similarity scanning",
      "Manual violation reporting capability",
    ],
  },
  {
    id: "1",
    title: "Pro Shield",
    description: "Deepfake scanning & real-time monitoring",
    price: "49",
    features: [
      "Vertex AI multi-modal pattern matching",
      "Automated DMCA Takedown Engine",
      "Geo-anomalies and bot-farm detection",
    ],
  },
  {
    id: "2",
    title: "Enterprise",
    description: "Custom licensing, API access, and dedicated support",
    price: null,
    features: [
      "Monitor up to 10M+ scale digital assets",
      "Direct API integration for ingestion",
      "Dedicated legal enforcement team",
    ],
  },
];

export const benefits = [
  {
    id: "0",
    title: "The Asset Vault",
    text: "A secure storage layer ensuring each uploaded GIF, image, or video is cryptographically linked to its rightful owner.",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
    details: "Secure, encrypted storage for high-value media. Every upload is automatically timestamped on an immutable ledger, creating a permanent record of ownership before public distribution. Supports dual-layer encryption for sensitive assets.",
  },
  {
    id: "1",
    title: "Fingerprinting Engine",
    text: "Generates robust perceptual signatures (pHash) that survive resizing, cropping, and format conversions.",
    backgroundUrl: "assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
    details: "Uses advanced perceptual hashing algorithms to create a unique digital signature of your media. Unlike standard hashes, Verity's fingerprints survive resizing, cropping, noise addition, and cross-platform compression, enabling tracking across the entire surface web.",
  },
  {
    id: "2",
    title: "Crawler Network",
    text: "Continuously scans global platforms (Reddit, YouTube, web endpoints) directly fetching candidate media.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
    details: "Distributed scanning nodes that monitor social media pipelines, open forums, and private media repositories. Operates 24/7 to identify candidates that match your vault fingerprints, with built-in deduplication and noise filtering.",
  },
  {
    id: "3",
    title: "AI Match Engine",
    text: "Evaluates multi-factor confidence signals spanning embeddings, Vertex AI, and deepfake generation likelihood.",
    backgroundUrl: "assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
    details: "A multi-modal intelligence layer using Vertex AI. It doesn't just look for pixel matches—it understands content context, identifies face swaps, and calculates a 'Deepfake Probability Score' for suspected manipulations.",
  },
  {
    id: "4",
    title: "Anomaly Detection",
    text: "Detects coordinated redistribution using Google Cloud ARIMA_PLUS models to flag unusual traffic spikes.",
    backgroundUrl: "assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
    details: "Monitors the global distribution velocity of your assets. Coordinated bot-farm activity or viral redistribution is flagged using time-series forecasting, allowing you to intercept misuse before it scales.",
  },
  {
    id: "5",
    title: "DMCA Automations",
    text: "Connects detected violations against rights databases, immediately drafting Gemini-assisted takedown requests.",
    backgroundUrl: "assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    details: "One-click legal enforcement. When a high-confidence violation is found, Verity drafts a formal takedown request tailored to the specific platform's requirements. Powered by Gemini to ensure legal accuracy and high success rates.",
  },
];

export const socials = [
  { id: "0", title: "Discord", iconUrl: discordBlack, url: "#" },
  { id: "1", title: "Twitter", iconUrl: twitter, url: "#" },
  { id: "2", title: "Instagram", iconUrl: instagram, url: "#" },
  { id: "3", title: "Telegram", iconUrl: telegram, url: "#" },
  { id: "4", title: "Facebook", iconUrl: facebook, url: "#" },
];
